---
galaxy_info:
  author: Grell Gragham
  description: Deploy Nginx to deb-based GNU/Linux system
  license: license (BSD)
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
